---
- hosts: dev 
  vars:
    build_number: "{{ lookup('env','UPSTREAM_BUILD_NUMBER') }}"
    dist_path: /apps/
    src_file: "/var/lib/jenkins/jobs/roaster_backend_build/builds/{{ build_number }}/archive/target/rpm/RPMS/noarch/sample_project-0.1-1.noarch.rpm"
    app_archive: "{{ dist_path }}/sample_project-0.1-1.noarch.rpm"
  become: true
  tasks:
  - name: Create Server Directory
    command: mkdir -p {{dist_path}}

  - name: Copy RPM
    copy:
      src: "{{ src_file }}"
      dest: "{{ app_archive }}"
      owner: root
      group: root
      mode: 0644

  - name: Stop Old Service
    command: service sample_project stop

  - name: if sample_project installed
    command: rpm -qa "sample_project"
    register: rpm_check

  - name: Uninstall sample_project
    command: rpm -e sample_project-0.1-1.noarch
    when: rpm_check.stdout.find('sample_project') != -1

  - name: Deploy sample_project
    command: rpm -i {{ app_archive }}

  - name: Delete Deployed RPM
    command: rm {{ app_archive }}
